name: resource_storage_example
description: "resource_storage example"
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  resource_storage: ^1.0.0

dev_dependencies:
  lints: ^3.0.0