name: resource_storage
description: "Base classes to implement resource storage for [cached_resource](https://pub.dev/packages/cached_resource) package."
version: 1.0.1
homepage: https://github.com/drstranges/resource_storage
repository: https://github.com/drstranges/resource_storage
issue_tracker: https://github.com/drstranges/resource_storage/issues
topics:
  - storage
  - cache

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0